id: aavdc_s3d

dataset: aavdc
visual_feature_type: ['s3d']
visual_feature_folder: ['/content/drive/MyDrive/University/01022-Final-Project/videos/howto100m_s3d_features/']
feature_dim: 1024
invalid_video_json: []
train_caption_file: data/aavdc/captiondata/aavdc_train.json
val_caption_file: data/aavdc/captiondata/aavdc_val.json
gt_file_for_auc: data/aavdc/captiondata/aavdc_val.json
gt_file_for_eval: ['data/aavdc/captiondata/aavdc_val.json']
gt_file_for_para_eval: ['data/aavdc/captiondata/para/para_aavdc_val.json']
eval_gt_file_for_grounding: data/aavdc/captiondata/grounding/aavdc_val_for_grounding.json
dict_file: data/aavdc/vocabulary_aavdc.json
vocab_size: 27895

huggingface_cache_dir: .cache
train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest
frame_embedding_num: 200

# model configs
num_queries: 100
batch_size: 8
eval_batch_size: 8
lr: 0.00005
learning_rate_decay_start: 8
learning_rate_decay_every: 3
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
epoch: 25
save_dir: /content/drive/MyDrive/University/01022-Final-Project/save
# grounding settings
eval_enable_grounding: True
# Text encoder
word_context_modeling_type: attention_pool
text_encoder_learning_strategy: frozen
text_encoder_lr: 0.00001
text_encoder_lr_decay_start: 8
text_encoder_lr_decay_every: 3
text_encoder_lr_decay_rate: 0.5
enable_layer_diff_text_feature: True
# Text Context Modeling
enable_word_context_modeling: True
enable_sentence_context_modeling: True
enable_sentence_pos_embedding: True
sentence_modeling_layer_num: 1

# contrastive loss
pretrained_language_model: roberta-base
enable_contrastive: True
enable_cross_video_cl: True
cl_schedule_time: [0, 2]
cl_schedule_val: [0, 0.1]
contrastive_loss_coef: 0.1
contrastive_loss_temperature: 0.1
contrastive_hidden_size: 128
eval_set_cost_class: 0

dec_layers: 2
enc_layers: 2
transformer_ff_dim: 512
transformer_dropout_prob: 0.1
caption_decoder_type: standard
cap_nheads: 1
cap_dec_n_points: 4
cap_num_feature_levels: 4
soft_attention: 1
att_hid_size: 512
ec_alpha: 1.0


with_box_refine: 1
fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
set_cost_cl: 2.0

caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 10
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1